name: Vercel Preview Deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.preview-url.outputs.preview_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > preview-url.txt
      - name: Set Output Variable
        id: preview-url
        run: echo "::set-output name=preview_url::$(cat preview-url.txt)"
  cypress-tests:
    needs: Deploy-Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cypress
        run: npm ci
      - name: Run Cypress Tests
        run: npm run cypress:run -- --config baseUrl="${{ needs.Deploy-Preview.outputs.preview_url }}"
