name: Cypress Tests With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        uses: cypress-io/github-action@v6
        with:
          start: vercel dev --token "$VERCEL_TOKEN"
