name: Cypress Tests With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: npm ci
      - name: Cypress Run
        run: npm run cypress:run
