name: Cypress Tests With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo $VERCEL_TOKEN
      - run: echo ${{ env.VERCEL_TOKEN }} "from env"
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: vercel dev --token ${{ env.VERCEL_TOKEN }}
